# Generated by Django 4.0.3 on 2022-05-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=256)),
                ('phone', models.IntegerField()),
                ('message', models.CharField(max_length=256)),
            ],
        ),
    ]
