# Generated by Django 4.0.3 on 2022-05-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
